# Generated by Django 5.2.15 on 2026-07-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('TOPUP', 'Top-up'), ('WITHDRAWAL', 'Withdrawal'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='ledger.transaction')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='ledger_entr_wallet__a8ebea_idx'), models.Index(fields=['transaction'], name='ledger_entr_transac_16a1ad_idx')],
            },
        ),
    ]
